<?php

// Arabic translation implementation script
// This script translates all English strings to proper Arabic

$enJsonPath = __DIR__ . '/lang/en.json';
$arJsonPath = __DIR__ . '/resources/lang/ar.json';
$langArJsonPath = __DIR__ . '/lang/ar.json';
$langArDir = __DIR__ . '/lang/ar';

// Read English translations
$enTranslations = json_decode(file_get_contents($enJsonPath), true);

// Arabic translations dictionary with proper terminology
$arabicTranslations = [
    // Common UI terms
    "Dashboard" => "لوحة التحكم",
    "Settings" => "الإعدادات",
    "Users" => "المستخدمون",
    "User" => "المستخدم",
    "Customers" => "العملاء",
    "Customer" => "العميل",
    "Subscription" => "الاشتراك",
    "Billing" => "الفوترة",
    "Payment" => "الدفع",
    "Invoice" => "الفاتورة",
    "Plan" => "الخطة",
    "Plans" => "الخطط",
    "Pricing" => "الأسعار",
    "Features" => "الميزات",
    "Support" => "الدعم",
    "Help" => "المساعدة",
    "Contact" => "اتصل بنا",
    "About" => "حول",
    "Home" => "الرئيسية",
    "Login" => "تسجيل الدخول",
    "Logout" => "تسجيل الخروج",
    "Register" => "التسجيل",
    "Sign In" => "تسجيل الدخول",
    "Sign Up" => "التسجيل",
    "Sign out" => "تسجيل الخروج",
    "Email" => "البريد الإلكتروني",
    "Password" => "كلمة المرور",
    "Name" => "الاسم",
    "Phone" => "الهاتف",
    "Address" => "العنوان",
    "Country" => "البلد",
    "City" => "المدينة",
    "Save" => "حفظ",
    "Cancel" => "إلغاء",
    "Delete" => "حذف",
    "Edit" => "تعديل",
    "Create" => "إنشاء",
    "Add" => "إضافة",
    "Remove" => "إزالة",
    "Update" => "تحديث",
    "Search" => "بحث",
    "Filter" => "تصفية",
    "Sort" => "ترتيب",
    "View" => "عرض",
    "Show" => "إظهار",
    "Hide" => "إخفاء",
    "Close" => "إغلاق",
    "Open" => "فتح",
    "Back" => "رجوع",
    "Next" => "التالي",
    "Previous" => "السابق",
    "Submit" => "إرسال",
    "Send" => "إرسال",
    "Receive" => "استلام",
    "Download" => "تنزيل",
    "Upload" => "رفع",
    "Export" => "تصدير",
    "Import" => "استيراد",
    "Copy" => "نسخ",
    "Paste" => "لصق",
    "Cut" => "قص",
    "Undo" => "تراجع",
    "Redo" => "إعادة",
    "Print" => "طباعة",
    "Refresh" => "تحديث",
    "Reload" => "إعادة تحميل",
    "Loading" => "جاري التحميل",
    "Please wait" => "الرجاء الانتظار",
    "Processing" => "جاري المعالجة",
    "Success" => "نجح",
    "Error" => "خطأ",
    "Warning" => "تحذير",
    "Info" => "معلومات",
    "Yes" => "نعم",
    "No" => "لا",
    "OK" => "موافق",
    "Confirm" => "تأكيد",
    "Deny" => "رفض",
    "Accept" => "قبول",
    "Decline" => "رفض",
    "Agree" => "موافقة",
    "Disagree" => "عدم موافقة",
    "Enable" => "تفعيل",
    "Disable" => "تعطيل",
    "Active" => "نشط",
    "Inactive" => "غير نشط",
    "Enabled" => "مفعل",
    "Disabled" => "معطل",
    "On" => "تشغيل",
    "Off" => "إيقاف",
    "True" => "صحيح",
    "False" => "خطأ",
    "All" => "الكل",
    "None" => "لا شيء",
    "Select" => "اختر",
    "Choose" => "اختر",
    "Selected" => "محدد",
    "Total" => "المجموع",
    "Subtotal" => "المجموع الفرعي",
    "Amount" => "المبلغ",
    "Price" => "السعر",
    "Cost" => "التكلفة",
    "Discount" => "خصم",
    "Tax" => "الضريبة",
    "Fee" => "الرسوم",
    "Credit" => "رصيد",
    "Credits" => "أرصدة",
    "Balance" => "الرصيد",
    "Account" => "الحساب",
    "Accounts" => "الحسابات",
    "Profile" => "الملف الشخصي",
    "Admin" => "المسؤول",
    "Administrator" => "المسؤول",
    "Role" => "الدور",
    "Roles" => "الأدوار",
    "Permission" => "الصلاحية",
    "Permissions" => "الصلاحيات",
    "Group" => "المجموعة",
    "Groups" => "المجموعات",
    "Team" => "الفريق",
    "Teams" => "الفرق",
    "Member" => "العضو",
    "Members" => "الأعضاء",
    "Owner" => "المالك",
    "Manager" => "المدير",
    "Employee" => "الموظف",
    "Client" => "العميل",
    "Clients" => "العملاء",
    "Guest" => "زائر",
    "Visitor" => "زائر",
    "User" => "المستخدم",
    "Users" => "المستخدمون",
    
    // AI terminology
    "AI" => "الذكاء الاصطناعي",
    "AI Chat" => "دردشة الذكاء الاصطناعي",
    "AI Chat Bot" => "بوت الدردشة بالذكاء الاصطناعي",
    "AI Text Generator" => "مولد النصوص بالذكاء الاصطناعي",
    "AI Image Generator" => "مولد الصور بالذكاء الاصطناعي",
    "AI Code Generator" => "مولد الأكواد بالذكاء الاصطناعي",
    "AI Speech To Text" => "تحويل الكلام إلى نص بالذكاء الاصطناعي",
    "AI Speech to Text" => "تحويل الكلام إلى نص بالذكاء الاصطناعي",
    "AI Vision" => "رؤية الذكاء الاصطناعي",
    "AI Voiceover" => "التعليق الصوتي بالذكاء الاصطناعي",
    "AI Writer" => "كاتب الذكاء الاصطناعي",
    "AI Writer Categories" => "فئات كاتب الذكاء الاصطناعي",
    "AI-Powered Generator" => "مولد مدعوم بالذكاء الاصطناعي",
    "AI Powered" => "مدعوم بالذكاء الاصطناعي",
    "AI Image" => "صورة الذكاء الاصطناعي",
    "AI Code" => "كود الذكاء الاصطناعي",
    "AI Name" => "اسم الذكاء الاصطناعي",
    "AI PDF" => "ملف PDF بالذكاء الاصطناعي",
    "AI Generator" => "مولد الذكاء الاصطناعي",
    "AI Hub" => "مركز الذكاء الاصطناعي",
    "AI Article Wizard" => "معالج المقالات بالذكاء الاصطناعي",
    "AI Chat Template" => "قالب دردشة الذكاء الاصطناعي",
    
    // Technical terms (keep in English where appropriate)
    "API" => "API",
    "API Key" => "مفتاح API",
    "JSON" => "JSON",
    "HTML" => "HTML",
    "CSS" => "CSS",
    "JavaScript" => "JavaScript",
    "PHP" => "PHP",
    "Laravel" => "Laravel",
    "OpenAI" => "OpenAI",
    "ChatGPT" => "ChatGPT",
    "GPT" => "GPT",
    "DALL-E" => "DALL-E",
    "Dall-E" => "Dall-E",
    "Stripe" => "Stripe",
    "PayPal" => "PayPal",
    "WhatsApp" => "WhatsApp",
    "Facebook" => "فيسبوك",
    "Instagram" => "إنستغرام",
    "Twitter" => "تويتر",
    "Telegram" => "تيليجرام",
    "Google" => "جوجل",
    "YouTube" => "يوتيوب",
    "GitHub" => "GitHub",
    "OAuth" => "OAuth",
    "Webhook" => "Webhook",
    "Token" => "رمز",
    "Tokens" => "الرموز",
    "Model" => "النموذج",
    "Models" => "النماذج",
    "Prompt" => "المطالبة",
    "Prompts" => "المطالبات",
    "Training" => "التدريب",
    "Embedding" => "التضمين",
    "Vector" => "متجه",
    "Knowledge Base" => "قاعدة المعرفة",
    "Workflow" => "سير العمل",
    "Automation" => "الأتمتة",
    "Integration" => "التكامل",
    "Endpoint" => "نقطة النهاية",
    "Database" => "قاعدة البيانات",
    "Server" => "الخادم",
    "Client" => "العميل",
    "Request" => "طلب",
    "Response" => "استجابة",
    "Header" => "رأس",
    "Body" => "نص",
    "Method" => "الطريقة",
    "GET" => "GET",
    "POST" => "POST",
    "PUT" => "PUT",
    "DELETE" => "DELETE",
    "PATCH" => "PATCH",
    "URL" => "رابط",
    "URI" => "URI",
    "HTTP" => "HTTP",
    "HTTPS" => "HTTPS",
    "SSL" => "SSL",
    "TLS" => "TLS",
    "FTP" => "FTP",
    "SSH" => "SSH",
    "SMTP" => "SMTP",
    "IMAP" => "IMAP",
    "POP3" => "POP3",
    "DNS" => "DNS",
    "IP" => "IP",
    "IPv4" => "IPv4",
    "IPv6" => "IPv6",
    "MAC" => "MAC",
    "UUID" => "UUID",
    "ID" => "معرف",
    "SQL" => "SQL",
    "NoSQL" => "NoSQL",
    "Redis" => "Redis",
    "MongoDB" => "MongoDB",
    "MySQL" => "MySQL",
    "PostgreSQL" => "PostgreSQL",
    "SQLite" => "SQLite",
    "AWS" => "AWS",
    "Azure" => "Azure",
    "Google Cloud" => "Google Cloud",
    "Docker" => "Docker",
    "Kubernetes" => "Kubernetes",
    "Linux" => "لينكس",
    "Windows" => "ويندوز",
    "macOS" => "macOS",
    "iOS" => "iOS",
    "Android" => "أندرويد",
    
    // Common phrases
    "Welcome" => "مرحباً",
    "Welcome back" => "مرحباً بعودتك",
    "Thank you" => "شكراً لك",
    "Please" => "الرجاء",
    "Sorry" => "آسف",
    "Congratulations" => "تهانينا",
    "Good luck" => "حظاً موفقاً",
    "Best regards" => "مع أطيب التحيات",
    "Sincerely" => "بخالص التقدير",
    "Regards" => "تحياتي",
    "Yours truly" => "خالص تقديري",
    "Dear" => "عزيزي",
    "Hello" => "مرحباً",
    "Hi" => "مرحباً",
    "Good morning" => "صباح الخير",
    "Good afternoon" => "مساء الخير",
    "Good evening" => "مساء الخير",
    "Good night" => "تصبح على خير",
    "See you" => "أراك لاحقاً",
    "Goodbye" => "وداعاً",
    "Bye" => "وداعاً",
    
    // Status messages
    "Success" => "نجح",
    "Failed" => "فشل",
    "Error" => "خطأ",
    "Warning" => "تحذير",
    "Info" => "معلومات",
    "Completed" => "مكتمل",
    "Pending" => "قيد الانتظار",
    "In Progress" => "قيد التنفيذ",
    "Cancelled" => "ملغي",
    "Rejected" => "مرفوض",
    "Approved" => "موافق عليه",
    "Verified" => "موثق",
    "Unverified" => "غير موثق",
    "Active" => "نشط",
    "Inactive" => "غير نشط",
    "Online" => "متصل",
    "Offline" => "غير متصل",
    "Available" => "متاح",
    "Unavailable" => "غير متاح",
    "Enabled" => "مفعل",
    "Disabled" => "معطل",
    "Visible" => "مرئي",
    "Hidden" => "مخفي",
    "Public" => "عام",
    "Private" => "خاص",
    "Read" => "قراءة",
    "Write" => "كتابة",
    "Execute" => "تنفيذ",
    "Read-only" => "قراءة فقط",
    "Write-only" => "كتابة فقط",
    
    // Time and date
    "Today" => "اليوم",
    "Yesterday" => "أمس",
    "Tomorrow" => "غداً",
    "This week" => "هذا الأسبوع",
    "Last week" => "الأسبوع الماضي",
    "Next week" => "الأسبوع القادم",
    "This month" => "هذا الشهر",
    "Last month" => "الشهر الماضي",
    "Next month" => "الشهر القادم",
    "This year" => "هذا العام",
    "Last year" => "العام الماضي",
    "Next year" => "العام القادم",
    "Date" => "التاريخ",
    "Time" => "الوقت",
    "DateTime" => "التاريخ والوقت",
    "Created At" => "تاريخ الإنشاء",
    "Updated At" => "تاريخ التحديث",
    "Deleted At" => "تاريخ الحذف",
    "Expires At" => "تاريخ الانتهاء",
    "Start Date" => "تاريخ البدء",
    "End Date" => "تاريخ الانتهاء",
    "Start Time" => "وقت البدء",
    "End Time" => "وقت الانتهاء",
    "Duration" => "المدة",
    "Period" => "الفترة",
    "Schedule" => "الجدول",
    "Calendar" => "التقويم",
    "Reminder" => "تذكير",
    
    // Numbers and quantities
    "Quantity" => "الكمية",
    "Number" => "الرقم",
    "Count" => "العدد",
    "Total" => "المجموع",
    "Sum" => "المجموع",
    "Average" => "المتوسط",
    "Minimum" => "الحد الأدنى",
    "Maximum" => "الحد الأقصى",
    "Range" => "النطاق",
    "Limit" => "الحد",
    "Quota" => "الحصة",
    "Capacity" => "السعة",
    "Size" => "الحجم",
    "Length" => "الطول",
    "Width" => "العرض",
    "Height" => "الارتفاع",
    "Weight" => "الوزن",
    "Volume" => "الحجم",
    "Area" => "المساحة",
    "Percentage" => "النسبة المئوية",
    "Percent" => "بالمئة",
    "Ratio" => "النسبة",
    "Rate" => "المعدل",
    "Speed" => "السرعة",
    "Frequency" => "التردد",
    
    // File and media
    "File" => "الملف",
    "Files" => "الملفات",
    "Folder" => "المجلد",
    "Folders" => "المجلدات",
    "Directory" => "الدليل",
    "Document" => "المستند",
    "Documents" => "المستندات",
    "Image" => "الصورة",
    "Images" => "الصور",
    "Photo" => "الصورة",
    "Photos" => "الصور",
    "Video" => "الفيديو",
    "Videos" => "الفيديوهات",
    "Audio" => "الصوت",
    "Music" => "الموسيقى",
    "Song" => "الأغنية",
    "Songs" => "الأغاني",
    "Album" => "الألبوم",
    "Albums" => "الألبومات",
    "Playlist" => "قائمة التشغيل",
    "Playlists" => "قوائم التشغيل",
    "Download" => "تنزيل",
    "Upload" => "رفع",
    "Share" => "مشاركة",
    "Copy" => "نسخ",
    "Move" => "نقل",
    "Rename" => "إعادة تسمية",
    "Delete" => "حذف",
    "Restore" => "استعادة",
    "Archive" => "أرشفة",
    "Compress" => "ضغط",
    "Extract" => "استخراج",
    
    // Navigation and layout
    "Menu" => "القائمة",
    "Navigation" => "التنقل",
    "Breadcrumb" => "مسار التنقل",
    "Sidebar" => "الشريط الجانبي",
    "Header" => "الرأس",
    "Footer" => "التذييل",
    "Content" => "المحتوى",
    "Body" => "النص",
    "Section" => "القسم",
    "Page" => "الصفحة",
    "Pages" => "الصفحات",
    "Tab" => "علامة التبويب",
    "Tabs" => "علامات Tab",
    "Panel" => "اللوحة",
    "Panels" => "اللوحات",
    "Card" => "البطاقة",
    "Cards" => "البطاقات",
    "List" => "القائمة",
    "Lists" => "القوائم",
    "Table" => "الجدول",
    "Tables" => "الجداول",
    "Grid" => "الشبكة",
    "Form" => "النموذج",
    "Forms" => "النماذج",
    "Input" => "الإدخال",
    "Inputs" => "المدخلات",
    "Output" => "الإخراج",
    "Outputs" => "المخرجات",
    "Field" => "الحقل",
    "Fields" => "الحقول",
    "Label" => "التسمية",
    "Labels" => "التسميات",
    "Button" => "الزر",
    "Buttons" => "الأزرار",
    "Link" => "الرابط",
    "Links" => "الروابط",
    "Icon" => "الأيقونة",
    "Icons" => "الأيقونات",
    "Image" => "الصورة",
    "Images" => "الصور",
    "Avatar" => "الصورة الرمزية",
    "Logo" => "الشعار",
    "Banner" => "الشريط",
    "Slider" => "شريط التمرير",
    "Carousel" => "دوار",
    "Modal" => "نافذة منبثقة",
    "Dialog" => "حوار",
    "Popup" => "نافذة منبثقة",
    "Tooltip" => "تلميح",
    "Dropdown" => "قائمة منسدلة",
    "Accordion" => "أكورديون",
    "Tabs" => "علامات التبويب",
    "Wizard" => "المعالج",
    "Step" => "الخطوة",
    "Steps" => "الخطوات",
    "Progress" => "التقدم",
    "Progress Bar" => "شريط التقدم",
    "Loading" => "جاري التحميل",
    "Spinner" => "مؤشر التحميل",
    "Skeleton" => "هيكل عظمي",
    "Placeholder" => "عنصر نائب",
    
    // Actions and operations
    "Action" => "الإجراء",
    "Actions" => "الإجراءات",
    "Operation" => "العملية",
    "Operations" => "العمليات",
    "Task" => "المهمة",
    "Tasks" => "المهام",
    "Job" => "الوظيفة",
    "Jobs" => "الوظائف",
    "Process" => "العملية",
    "Processes" => "العمليات",
    "Workflow" => "سير العمل",
    "Workflows" => "سير العمل",
    "Pipeline" => "خط الأنابيب",
    "Pipelines" => "خطوط الأنابيب",
    "Queue" => "الطابور",
    "Queues" => "الطوابير",
    "Schedule" => "الجدولة",
    "Schedules" => "الجداول",
    "Trigger" => "المشغل",
    "Triggers" => "المشغلات",
    "Event" => "الحدث",
    "Events" => "الأحداث",
    "Listener" => "المستمع",
    "Listeners" => "المستمعين",
    "Observer" => "الملاحظ",
    "Observers" => "الملاحظين",
    "Hook" => "خطاف",
    "Hooks" => "الخطافات",
    "Filter" => "فلتر",
    "Filters" => "الفلاتر",
    "Middleware" => "البرمجيات الوسيطة",
    "Service" => "الخدمة",
    "Services" => "الخدمات",
    "Provider" => "المزود",
    "Providers" => "المزودين",
    "Repository" => "المستودع",
    "Repositories" => "المستودعات",
    "Model" => "النموذج",
    "Models" => "النماذج",
    "Controller" => "المتحكم",
    "Controllers" => "المتحكمات",
    "View" => "العرض",
    "Views" => "العروض",
    "Component" => "المكون",
    "Components" => "المكونات",
    "Module" => "الوحدة",
    "Modules" => "الوحدات",
    "Package" => "الحزمة",
    "Packages" => "الحزم",
    "Library" => "المكتبة",
    "Libraries" => "المكتبات",
    "Plugin" => "الإضافة",
    "Plugins" => "الإضافات",
    "Extension" => "الامتداد",
    "Extensions" => "الامتدادات",
    "Theme" => "المظهر",
    "Themes" => "المظاهر",
    "Template" => "القالب",
    "Templates" => "القوالب",
    "Layout" => "التخطيط",
    "Layouts" => "التخطيطات",
    "Style" => "النمط",
    "Styles" => "الأنماط",
    "Script" => "السكريبت",
    "Scripts" => "السكريبتات",
    "Asset" => "الأصل",
    "Assets" => "الأصول",
    "Resource" => "المورد",
    "Resources" => "الموارد",
];

// Function to translate a string to Arabic
function translateToArabic($text, $dictionary) {
    // Check if exact match exists in dictionary
    if (isset($dictionary[$text])) {
        return $dictionary[$text];
    }
    
    // Check for partial matches (contains)
    foreach ($dictionary as $english => $arabic) {
        if (stripos($text, $english) !== false) {
            return str_ireplace($english, $arabic, $text);
        }
    }
    
    // If no match found, return original (will need manual review)
    return $text;
}

// Translate all keys
$arabicJson = [];
$translatedCount = 0;
$untranslatedCount = 0;

foreach ($enTranslations as $key => $value) {
    if (is_string($value) && !empty($value)) {
        $translated = translateToArabic($value, $arabicTranslations);
        $arabicJson[$key] = $translated;
        
        if ($translated !== $value) {
            $translatedCount++;
        } else {
            $untranslatedCount++;
        }
    } else {
        $arabicJson[$key] = $value;
    }
}

// Write to resources/lang/ar.json
file_put_contents($arJsonPath, json_encode($arabicJson, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE));

// Create lang/ar directory if it doesn't exist
if (!is_dir($langArDir)) {
    mkdir($langArDir, 0755, true);
}

// Write to lang/ar.json
file_put_contents($langArJsonPath, json_encode($arabicJson, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE));

echo "Translation complete!\n";
echo "Total keys: " . count($enTranslations) . "\n";
echo "Translated: $translatedCount\n";
echo "Untranslated (needs manual review): $untranslatedCount\n";
echo "\nFiles created:\n";
echo "- resources/lang/ar.json\n";
echo "- lang/ar.json\n";
echo "\nNext steps:\n";
echo "1. Review untranslated keys and manually translate them\n";
echo "2. Create lang/ar/auth.php, validation.php, passwords.php, pagination.php\n";
